import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const {data: tasks, isLoading, refetch: taskRefetch} = api.task.returnAll.useQuery();
  const mutation = api.task.create.useMutation({
    onSuccess() {
      taskRefetch();
    }
  });
  const finishMutation = api.task.finish.useMutation({
    onSuccess() {
      taskRefetch();
    }
  })

  const Submit = async (event: any) => {
    event.preventDefault();
    await mutation.mutate({task: event.target.task.value})
    event.target.task.value = ''
  }

  const Finish = async (val: string) => {
    await finishMutation.mutate({id: val})
  }

  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="m-2">
          <form className="flex gap-2" onSubmit={Submit}>
            <input className="w-full px-2 border text-black rounded-full" name='task' type={'text'} placeholder="Enter your task name"/>
            <button className="bg-purple-800 text-white rounded-full px-3 py-2" type="submit">submit</button>
          </form>
        </div>
        <div className="flex flex-row flex-wrap m-2 gap-2">
          {!isLoading && tasks && tasks.map((task, ind)=>(
            <div key={ind} className="relative rounded bg-gray-300 h-[16rem] w-[16rem]">
            <h1 className="text-3xl m-2">Task {ind}: {task.title}</h1>
            <button onClick={()=>Finish(task.id)} className="absolute bottom-2 text-white mx-2 w-[15rem] h-[2.5rem] rounded-full bg-blue-500 active:bg-blue-600">Finished</button>
          </div>
          ))}
        </div>
      </main>
    </>
  );
}
